 [ -f next-env.d.ts ] || cat > next-env.d.ts <<'TS'
// This file is required for Next.js TypeScript support.
// Do not edit this file directly.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
TS
